"""Check catalog + generator for Phase 1 (sample-data-driven) audits.

Each entry in CHECK_CATALOG describes one audit check: its category, a
relative importance `weight` within that category (so trivial checks like
"has a favicon" can't tank a score the way "has HTTPS" should be able to),
and a set of possible outcomes with realistic business-friendly copy.

`run_checks(site_profile)` deterministically rolls an outcome for every
check using a seeded RNG (seeded from the URL), so the same URL always
produces the same demo audit. This function is the seam Phase 2 replaces
with checks driven by real crawl data — the output shape (list of check
dicts) stays the same either way, so scoring.py and recommendations.py
never need to change.
"""
import random

STATUS_PASS = "PASS"
STATUS_WARNING = "WARNING"
STATUS_FAIL = "FAIL"
STATUS_NOT_DETECTED = "NOT_DETECTED"
STATUS_NOT_APPLICABLE = "NOT_APPLICABLE"


def _pick(rng: random.Random, outcomes: dict) -> str:
    """Pick a status key from an outcomes dict using each entry's 'prob' weight."""
    keys = list(outcomes.keys())
    weights = [outcomes[k]["prob"] for k in keys]
    return rng.choices(keys, weights=weights, k=1)[0]


CHECK_CATALOG = [
    # ---------------- ON-PAGE SEO ----------------
    dict(category="on_page_seo", key="title_tag", name="Title Tag", weight=3,
         outcomes={
             STATUS_PASS: dict(prob=50, result="Your page has a well-optimized title tag.",
                                raw="56 characters", expected="50-60 characters",
                                why="A clear, well-sized title tag helps search engines and searchers understand your page at a glance, which directly affects click-through rates from search results."),
             STATUS_WARNING: dict(prob=35, result="Your title tag is present but not ideally sized.",
                                   raw="38 characters", expected="50-60 characters",
                                   why="Titles that are too short waste an opportunity to describe your page; titles that are too long get cut off in search results.",
                                   rec_title="Optimize Title Tag Length", action="Rewrite the title tag to fall between 50-60 characters while including your main service and location.",
                                   impact="Search visibility & click-through rate", effort="Low", difficulty="Low"),
             STATUS_FAIL: dict(prob=15, result="Your page is missing a title tag.",
                                raw="Not found", expected="50-60 characters",
                                why="Without a title tag, search engines have to guess what your page is about, which typically hurts rankings and click-through rates.",
                                rec_title="Add a Title Tag", action="Add a unique, descriptive title tag to every important page.",
                                impact="Search visibility & rankings", effort="Low", difficulty="Low"),
         }),
    dict(category="on_page_seo", key="meta_description", name="Meta Description", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=45, result="Your meta description is present and well-sized.",
                                raw="148 characters", expected="120-160 characters",
                                why="A good meta description acts like ad copy in search results and can improve your click-through rate."),
             STATUS_WARNING: dict(prob=35, result="Your meta description is present but exceeds the ideal length.",
                                   raw="249 characters", expected="120-160 characters",
                                   why="Meta descriptions that are too long may get truncated in search results, cutting off your call to action.",
                                   rec_title="Shorten Meta Description", action="Rewrite the meta description to be between 120-160 characters, highlighting your key differentiator.",
                                   impact="Search click-through rate", effort="Low", difficulty="Low"),
             STATUS_FAIL: dict(prob=20, result="Your page is missing a meta description.",
                                raw="Not found", expected="120-160 characters",
                                why="Without a meta description, search engines will auto-generate one from your page text, which is often less compelling.",
                                rec_title="Add Meta Descriptions", action="Write a unique, benefit-focused meta description for every important page.",
                                impact="Search click-through rate", effort="Low", difficulty="Low"),
         }),
    dict(category="on_page_seo", key="h1_tag", name="H1 Header Tag", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=70, result="Your page has a single, clear H1 tag.", raw="1 H1 tag found", expected="Exactly 1 H1 tag",
                                why="The H1 tag tells both visitors and search engines the main topic of the page."),
             STATUS_FAIL: dict(prob=30, result="Your page is missing an H1 tag, or has multiple conflicting H1 tags.", raw="0 H1 tags found", expected="Exactly 1 H1 tag",
                                why="Missing or duplicate H1 tags make it harder for search engines to understand your page's main topic.",
                                rec_title="Fix H1 Header Tag Usage", action="Ensure every page has exactly one H1 tag summarizing its main topic.",
                                impact="Content clarity & rankings", effort="Low", difficulty="Low"),
         }),
    dict(category="on_page_seo", key="heading_structure", name="H2-H6 Header Structure", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=60, result="Your page makes good use of multiple heading levels.", raw="H2: 6, H3: 4, H4: 2", expected="Logical H2-H6 hierarchy",
                                why="A clear heading hierarchy makes content easier to scan for both readers and search engines."),
             STATUS_WARNING: dict(prob=40, result="Your page uses headings, but the hierarchy is inconsistent.", raw="H2 skipped, H3 used directly", expected="Logical H2-H6 hierarchy",
                                   why="An inconsistent heading structure can confuse search engines about which sections are most important.",
                                   rec_title="Improve Heading Hierarchy", action="Reorganize headings so H2s introduce major sections and H3-H6 nest logically beneath them.",
                                   impact="Content structure & readability", effort="Low", difficulty="Low"),
         }),
    dict(category="on_page_seo", key="keyword_consistency", name="Keyword / Topic Consistency", weight=3,
         outcomes={
             STATUS_PASS: dict(prob=40, result="Your main topics are consistently reflected across title, headings, and content.", raw="Consistent across tags", expected="Consistent topical focus",
                                why="When your core topics appear consistently across key HTML elements, search engines have a clearer signal of what you should rank for."),
             STATUS_WARNING: dict(prob=45, result="Your page's main topics are not well distributed across important HTML tags.", raw="Present in content only", expected="Present in title, meta, headings & content",
                                   why="If your core topics only appear in body text but not in titles or headings, you may be missing easy ranking opportunities.",
                                   rec_title="Improve Keyword Placement Across Key Tags", action="Work your primary services/topics naturally into the title, meta description, and headings.",
                                   impact="Topical relevance & rankings", effort="Medium", difficulty="Low"),
             STATUS_FAIL: dict(prob=15, result="No clear, consistent topical focus was detected.", raw="Inconsistent/diluted", expected="Consistent topical focus",
                                why="Without a clear topical focus, search engines struggle to know which searches your page should appear for.",
                                rec_title="Establish Clear Page Topics", action="Define 1-3 primary topics per page and reinforce them across title, headings, and content.",
                                impact="Topical relevance & rankings", effort="Medium", difficulty="Medium"),
         }),
    dict(category="on_page_seo", key="content_length", name="Content Length & Depth", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=45, result="Your page has substantial, topic-relevant content.", raw="~950 words", expected="Sufficient depth for topic & intent",
                                why="Pages with meaningful depth tend to answer more visitor questions and are more likely to satisfy search intent."),
             STATUS_WARNING: dict(prob=40, result="Your page content is on the thin side for its topic.", raw="~220 words", expected="Sufficient depth for topic & intent",
                                   why="Thin content may not fully answer visitor questions, which can hurt both rankings and conversion.",
                                   rec_title="Increase Page Content Depth", action="Expand key pages with more detail on services, benefits, process, and FAQs.",
                                   impact="Search relevance & user engagement", effort="Medium", difficulty="Low"),
             STATUS_FAIL: dict(prob=15, result="Your page has very little text content.", raw="~60 words", expected="Sufficient depth for topic & intent",
                                why="Extremely thin pages give search engines very little to work with and often struggle to rank at all.",
                                rec_title="Add Substantial Page Content", action="Add meaningful, unique content that explains your services, service area, and value proposition.",
                                impact="Search relevance & rankings", effort="Medium", difficulty="Medium"),
         }),
    dict(category="on_page_seo", key="image_alt_text", name="Image Alt Attributes", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=35, result="Most images have descriptive alt attributes.", raw="18/20 images", expected="All meaningful images", why="Alt text helps search engines understand images and improves accessibility for visitors using screen readers."),
             STATUS_WARNING: dict(prob=45, result="Some images are missing alt attributes.", raw="9/20 images", expected="All meaningful images",
                                   why="Missing alt text is a minor but easy-to-fix accessibility and SEO gap.",
                                   rec_title="Add Alt Attributes to All Images", action="Add descriptive alt text to every meaningful image, including your logo and service photos.",
                                   impact="Accessibility & image search", effort="Low", difficulty="Low"),
             STATUS_FAIL: dict(prob=20, result="Most images are missing alt attributes.", raw="2/20 images", expected="All meaningful images",
                                why="Without alt text, search engines and screen readers can't interpret your images at all.",
                                rec_title="Add Alt Attributes to All Images", action="Add descriptive alt text to every meaningful image, including your logo and service photos.",
                                impact="Accessibility & image search", effort="Low", difficulty="Low"),
         }),
    dict(category="on_page_seo", key="url_structure", name="URL Structure", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=65, result="Your URLs are clean and human-readable.", raw="/services/paint-correction", expected="Descriptive, hyphenated URLs",
                                why="Clean URLs are easier for visitors to trust and share, and give search engines an extra relevance signal."),
             STATUS_WARNING: dict(prob=35, result="Some URLs contain unnecessary parameters or unclear structure.", raw="/page?id=482", expected="Descriptive, hyphenated URLs",
                                   why="Unclear URLs are harder for visitors to trust and give search engines less context about the page.",
                                   rec_title="Clean Up URL Structure", action="Use short, descriptive, hyphenated URLs for important pages going forward.",
                                   impact="User trust & crawlability", effort="Medium", difficulty="Medium"),
         }),
    dict(category="on_page_seo", key="internal_linking", name="Internal Linking", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=55, result="Your page links well to other relevant pages on your site.", raw="8 internal links", expected="Meaningful internal linking",
                                why="Internal links help visitors discover more of your content and help search engines understand site structure."),
             STATUS_WARNING: dict(prob=45, result="Your page has very few internal links to other pages.", raw="1 internal link", expected="Meaningful internal linking",
                                   why="Limited internal linking makes it harder for visitors and search engines to find your other important pages.",
                                   rec_title="Improve Internal Linking", action="Add contextual links from this page to related services, locations, or blog content.",
                                   impact="Site structure & page authority flow", effort="Low", difficulty="Low"),
         }),

    # ---------------- TECHNICAL SEO ----------------
    dict(category="technical_seo", key="https", name="HTTPS", weight=3,
         outcomes={
             STATUS_PASS: dict(prob=85, result="Your website loads securely over HTTPS.", raw="HTTPS enabled", expected="HTTPS enabled",
                                why="HTTPS is a baseline trust and ranking signal, and browsers flag non-HTTPS sites as 'Not Secure'."),
             STATUS_FAIL: dict(prob=15, result="Your website does not load over HTTPS.", raw="HTTP only", expected="HTTPS enabled",
                                why="Without HTTPS, browsers warn visitors your site isn't secure, which damages trust and can hurt rankings.",
                                rec_title="Enable HTTPS Site-Wide", action="Install an SSL certificate and force all traffic to HTTPS.",
                                impact="Trust, security & rankings", effort="Low", difficulty="Low"),
         }),
    dict(category="technical_seo", key="http_to_https_redirect", name="HTTP to HTTPS Redirect", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=75, result="HTTP requests correctly redirect to HTTPS.", raw="301 redirect in place", expected="301 redirect to HTTPS",
                                why="This ensures visitors and search engines always land on the secure version of your site."),
             STATUS_WARNING: dict(prob=25, result="HTTP does not cleanly redirect to HTTPS.", raw="No redirect detected", expected="301 redirect to HTTPS",
                                   why="Without a redirect, some visitors or old links may load an insecure, unindexed version of your site.",
                                   rec_title="Add HTTP to HTTPS Redirect", action="Configure a site-wide 301 redirect from HTTP to HTTPS.",
                                   impact="Security & duplicate content prevention", effort="Low", difficulty="Low"),
         }),
    dict(category="technical_seo", key="robots_txt", name="Robots.txt", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=60, result="A robots.txt file was found and is properly configured.", raw="/robots.txt found", expected="Valid robots.txt",
                                why="Robots.txt gives search engines guidance on which parts of your site to crawl."),
             STATUS_NOT_DETECTED: dict(prob=40, result="No robots.txt file was found.", raw="Not found", expected="Valid robots.txt",
                                        why="Without robots.txt, search engines will crawl using default behavior, which is usually fine but leaves you without explicit control.",
                                        rec_title="Add a Robots.txt File", action="Create a robots.txt file to guide search engine crawling behavior.",
                                        impact="Crawl efficiency", effort="Low", difficulty="Low"),
         }),
    dict(category="technical_seo", key="xml_sitemap", name="XML Sitemap", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=55, result="An XML sitemap was found.", raw="/sitemap.xml found", expected="Valid XML sitemap",
                                why="A sitemap helps search engines discover and index all of your important pages efficiently."),
             STATUS_NOT_DETECTED: dict(prob=45, result="No XML sitemap was found.", raw="Not found", expected="Valid XML sitemap",
                                        why="Without a sitemap, search engines rely solely on links to discover your pages, which can slow down indexing of new content.",
                                        rec_title="Implement an XML Sitemap File", action="Generate an XML sitemap and submit it in Google Search Console.",
                                        impact="Search engine crawlability", effort="Low", difficulty="Low"),
         }),
    dict(category="technical_seo", key="canonical_tag", name="Canonical Tag", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=60, result="Canonical tags are correctly implemented.", raw="Self-referencing canonical present", expected="Valid canonical tag",
                                why="Canonical tags prevent duplicate content issues when multiple URLs show similar content."),
             STATUS_WARNING: dict(prob=25, result="Canonical tag is present but may be misconfigured.", raw="Points to different domain variant", expected="Self-referencing canonical",
                                   why="A misconfigured canonical can tell search engines to index the wrong version of your page.",
                                   rec_title="Fix Canonical Tag Configuration", action="Ensure canonical tags point to the correct preferred URL for each page.",
                                   impact="Duplicate content prevention", effort="Low", difficulty="Medium"),
             STATUS_NOT_DETECTED: dict(prob=15, result="No canonical tag was found.", raw="Not found", expected="Self-referencing canonical",
                                        why="Without canonical tags, similar or duplicate pages could compete against each other in search results.",
                                        rec_title="Add Canonical Tags", action="Add self-referencing canonical tags to all indexable pages.",
                                        impact="Duplicate content prevention", effort="Low", difficulty="Low"),
         }),
    dict(category="technical_seo", key="noindex_directive", name="Noindex Directive", weight=3,
         outcomes={
             STATUS_PASS: dict(prob=90, result="Your important pages are indexable (no blocking noindex directive found).", raw="No noindex found", expected="No noindex on important pages",
                                why="This confirms search engines are allowed to index and rank your important pages."),
             STATUS_FAIL: dict(prob=10, result="A noindex directive was found on an important page.", raw="noindex meta tag present", expected="No noindex on important pages",
                                why="A noindex tag tells search engines to exclude the page entirely from search results, which can silently remove key pages from Google.",
                                rec_title="Remove Unintended Noindex Directive", action="Remove the noindex tag/header from pages that should appear in search results.",
                                impact="Search visibility", effort="Low", difficulty="Low"),
         }),
    dict(category="technical_seo", key="structured_data_org", name="Organization / LocalBusiness Schema", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=35, result="Organization/LocalBusiness structured data was found.", raw="LocalBusiness schema detected", expected="Organization or LocalBusiness schema",
                                why="Structured data helps search engines (and increasingly AI assistants) clearly understand who you are and what you do."),
             STATUS_NOT_DETECTED: dict(prob=65, result="No Organization or LocalBusiness structured data was found.", raw="Not found", expected="Organization or LocalBusiness schema",
                                        why="Without structured data, search engines and AI tools have to infer your business details from unstructured text, which is less reliable.",
                                        rec_title="Add LocalBusiness Structured Data", action="Implement LocalBusiness (or Organization) schema markup with name, address, phone, and hours.",
                                        impact="Search & AI entity recognition", effort="Medium", difficulty="Medium"),
         }),
    dict(category="technical_seo", key="mobile_viewport", name="Mobile Viewport Tag", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=85, result="A mobile viewport meta tag is present.", raw="width=device-width", expected="Responsive viewport tag",
                                why="The viewport tag is required for your site to render correctly and scale properly on phones and tablets."),
             STATUS_FAIL: dict(prob=15, result="No mobile viewport meta tag was found.", raw="Not found", expected="Responsive viewport tag",
                                why="Without this tag, your site may display as a shrunken desktop layout on mobile devices, hurting usability.",
                                rec_title="Add a Mobile Viewport Meta Tag", action="Add a responsive viewport meta tag to the site template.",
                                impact="Mobile usability & rankings", effort="Low", difficulty="Low"),
         }),
    dict(category="technical_seo", key="http_protocol", name="HTTP/2 or HTTP/3 Support", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=70, result="Your server supports a modern HTTP protocol version.", raw="HTTP/2", expected="HTTP/2 or HTTP/3",
                                why="Modern protocols allow browsers to load your pages faster through better connection handling."),
             STATUS_NOT_DETECTED: dict(prob=30, result="Unable to confirm HTTP/2 or HTTP/3 support.", raw="HTTP/1.1 detected", expected="HTTP/2 or HTTP/3",
                                        why="Older protocols can mean slightly slower page loads, especially on pages with many resources.",
                                        rec_title="Upgrade Server to HTTP/2 or HTTP/3", action="Work with your host/CDN to enable HTTP/2 or HTTP/3.",
                                        impact="Page load speed", effort="Low", difficulty="Medium"),
         }),

    # ---------------- PERFORMANCE ----------------
    dict(category="performance", key="mobile_performance", name="Mobile Performance Score", weight=3,
         outcomes={
             STATUS_PASS: dict(prob=30, result="Mobile performance is strong.", raw="Score: 88/100", expected="90+",
                                why="Fast mobile load times reduce bounce rates and are a confirmed Google ranking factor."),
             STATUS_WARNING: dict(prob=45, result="Mobile performance has room for improvement.", raw="Score: 61/100", expected="90+",
                                   why="Slower mobile pages tend to lose visitors before they even see your content, and can be outranked by faster competitors.",
                                   rec_title="Improve Mobile Page Speed", action="Optimize images, reduce render-blocking scripts, and enable caching to speed up mobile load times.",
                                   impact="User experience & search rankings", effort="Medium", difficulty="Medium"),
             STATUS_FAIL: dict(prob=25, result="Mobile performance is significantly below recommended levels.", raw="Score: 34/100", expected="90+",
                                why="Slow mobile pages cause many visitors to leave before the page even finishes loading.",
                                rec_title="Improve Mobile Page Speed", action="Prioritize a mobile performance audit — likely candidates are unoptimized images, excess scripts, and slow server response.",
                                impact="User experience & search rankings", effort="High", difficulty="Medium"),
         }),
    dict(category="performance", key="desktop_performance", name="Desktop Performance Score", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=45, result="Desktop performance is strong.", raw="Score: 92/100", expected="90+", why="Fast desktop load times support a better overall user experience."),
             STATUS_WARNING: dict(prob=40, result="Desktop performance has room for improvement.", raw="Score: 74/100", expected="90+",
                                   why="Slower desktop pages can still frustrate visitors and impact conversion rates.",
                                   rec_title="Optimize Desktop Page Speed", action="Compress images and minify CSS/JS to improve desktop load times.",
                                   impact="User experience", effort="Medium", difficulty="Low"),
             STATUS_FAIL: dict(prob=15, result="Desktop performance is significantly below recommended levels.", raw="Score: 41/100", expected="90+",
                                why="Very slow desktop pages can meaningfully hurt conversion rates.",
                                rec_title="Optimize Desktop Page Speed", action="Investigate render-blocking resources and server response time.",
                                impact="User experience & conversions", effort="Medium", difficulty="Medium"),
         }),
    dict(category="performance", key="lcp", name="Largest Contentful Paint (LCP)", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=40, result="Largest Contentful Paint is within the recommended range.", raw="2.1s", expected="< 2.5s", why="LCP measures how quickly your main content becomes visible — a core Google Core Web Vital."),
             STATUS_WARNING: dict(prob=40, result="Largest Contentful Paint is slower than recommended.", raw="3.4s", expected="< 2.5s",
                                   why="A slow LCP means visitors wait longer to see your main content, which can increase bounce rates.",
                                   rec_title="Improve Largest Contentful Paint", action="Optimize your largest above-the-fold image or text block and reduce server response time.",
                                   impact="Core Web Vitals & user experience", effort="Medium", difficulty="Medium"),
             STATUS_FAIL: dict(prob=20, result="Largest Contentful Paint is well above the recommended range.", raw="5.8s", expected="< 2.5s",
                                why="A very slow LCP significantly hurts both user experience and Google's Core Web Vitals ranking signal.",
                                rec_title="Improve Largest Contentful Paint", action="Prioritize loading of the hero image/text and reduce blocking scripts.",
                                impact="Core Web Vitals & user experience", effort="High", difficulty="Medium"),
         }),
    dict(category="performance", key="cls", name="Cumulative Layout Shift (CLS)", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=55, result="Cumulative Layout Shift is within the recommended range.", raw="0.05", expected="< 0.1", why="Low layout shift means your page doesn't jump around as it loads, which is important for usability."),
             STATUS_WARNING: dict(prob=45, result="Cumulative Layout Shift is higher than recommended.", raw="0.22", expected="< 0.1",
                                   why="Visible content shifting during load frustrates users and can cause accidental clicks.",
                                   rec_title="Reduce Layout Shift", action="Set explicit width/height on images and ads, and avoid injecting content above existing content.",
                                   impact="User experience & Core Web Vitals", effort="Medium", difficulty="Medium"),
         }),
    dict(category="performance", key="page_size", name="Total Page Size", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=40, result="Page size is reasonable.", raw="1.8 MB", expected="< 2.5 MB", why="Smaller page sizes generally load faster, especially on mobile connections."),
             STATUS_WARNING: dict(prob=45, result="Page size is larger than ideal.", raw="4.2 MB", expected="< 2.5 MB",
                                   why="Larger page sizes take longer to download, especially for visitors on mobile networks.",
                                   rec_title="Reduce Total Page Size", action="Compress and resize images, and remove unused CSS/JS.",
                                   impact="Page load speed", effort="Medium", difficulty="Low"),
             STATUS_FAIL: dict(prob=15, result="Page size is significantly larger than recommended.", raw="9.6 MB", expected="< 2.5 MB",
                                why="Very large pages create a poor experience for mobile visitors and slow-connection users.",
                                rec_title="Reduce Total Page Size", action="Audit and compress large media files; consider lazy-loading below-the-fold images.",
                                impact="Page load speed", effort="Medium", difficulty="Medium"),
         }),
    dict(category="performance", key="image_optimization", name="Image Optimization", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=35, result="Images appear to be well optimized/compressed.", raw="Avg. 85kb/image", expected="Compressed, modern formats",
                                why="Optimized images load faster without a noticeable quality loss."),
             STATUS_WARNING: dict(prob=50, result="Several images are not optimized/compressed.", raw="Avg. 620kb/image", expected="Compressed, modern formats",
                                   why="Unoptimized images are one of the most common causes of slow page loads.",
                                   rec_title="Optimize Images", action="Compress images and convert to modern formats like WebP where possible.",
                                   impact="Page load speed", effort="Low", difficulty="Low"),
             STATUS_FAIL: dict(prob=15, result="Most images are large and unoptimized.", raw="Avg. 1.4MB/image", expected="Compressed, modern formats",
                                why="Very large images meaningfully slow down every page they appear on.",
                                rec_title="Optimize Images", action="Compress and resize all images; convert to WebP/AVIF where possible.",
                                impact="Page load speed", effort="Medium", difficulty="Low"),
         }),
    dict(category="performance", key="minification", name="CSS/JS Minification", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=45, result="CSS and JavaScript files appear to be minified.", raw="Minified", expected="Minified", why="Minified files are smaller and load faster."),
             STATUS_WARNING: dict(prob=55, result="CSS and/or JavaScript files are not minified.", raw="Unminified", expected="Minified",
                                   why="Unminified files are larger than necessary and slow down page loads slightly.",
                                   rec_title="Minify CSS & JavaScript", action="Enable minification for CSS and JS assets, often available as a plugin or build step.",
                                   impact="Page load speed", effort="Low", difficulty="Low"),
         }),

    # ---------------- USABILITY / MOBILE ----------------
    dict(category="usability_mobile", key="responsive_design", name="Responsive Design", weight=3,
         outcomes={
             STATUS_PASS: dict(prob=70, result="Your site adapts well to different screen sizes.", raw="Responsive layout detected", expected="Fully responsive",
                                why="A responsive design ensures visitors have a good experience regardless of device, which is essential since most searches happen on mobile."),
             STATUS_WARNING: dict(prob=30, result="Some page elements do not adapt well to smaller screens.", raw="Partial responsiveness", expected="Fully responsive",
                                   why="Layout issues on mobile can frustrate the majority of your visitors and increase bounce rates.",
                                   rec_title="Fix Mobile Responsiveness Issues", action="Review and fix layout elements that break or overflow on mobile screens.",
                                   impact="Mobile user experience", effort="Medium", difficulty="Medium"),
         }),
    dict(category="usability_mobile", key="tap_targets", name="Tap Target Sizing", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=55, result="Buttons and links are appropriately sized for touch.", raw="Adequately spaced", expected="Adequately sized/spaced tap targets",
                                why="Properly sized tap targets prevent frustrating mis-taps on mobile devices."),
             STATUS_WARNING: dict(prob=45, result="Some buttons or links are too small or too close together for comfortable tapping.", raw="Some targets < 40px", expected="Adequately sized/spaced tap targets",
                                   why="Small tap targets are a common source of mobile usability frustration.",
                                   rec_title="Increase Tap Target Sizes", action="Increase spacing and size for buttons/links used on mobile.",
                                   impact="Mobile usability", effort="Low", difficulty="Low"),
         }),
    dict(category="usability_mobile", key="font_readability", name="Font Readability", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=65, result="Font sizes are legible without zooming.", raw="16px base font", expected=">=16px base font",
                                why="Readable text without zooming keeps visitors engaged rather than frustrated."),
             STATUS_WARNING: dict(prob=35, result="Some text may be too small to read comfortably on mobile.", raw="12px base font", expected=">=16px base font",
                                   why="Small text forces visitors to zoom in, creating friction that can drive them away.",
                                   rec_title="Increase Base Font Size", action="Increase base font size to at least 16px for mobile readability.",
                                   impact="Mobile usability", effort="Low", difficulty="Low"),
         }),
    dict(category="usability_mobile", key="mobile_navigation", name="Mobile Navigation", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=60, result="Navigation is clear and usable on mobile.", raw="Mobile menu present", expected="Clear, accessible mobile nav",
                                why="Easy navigation helps mobile visitors quickly find what they need, supporting conversions."),
             STATUS_WARNING: dict(prob=40, result="Mobile navigation could be simplified.", raw="Nested/complex menu", expected="Clear, accessible mobile nav",
                                   why="Complex mobile navigation can frustrate visitors trying to find services or contact info quickly.",
                                   rec_title="Simplify Mobile Navigation", action="Streamline the mobile menu to highlight your most important pages.",
                                   impact="Mobile usability & conversions", effort="Medium", difficulty="Low"),
         }),
    dict(category="usability_mobile", key="form_accessibility", name="Form Accessibility", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=50, result="Forms are accessible and easy to complete.", raw="Labeled fields detected", expected="Labeled, accessible forms",
                                why="Accessible forms make it easier for all visitors — including those using assistive technology — to contact you."),
             STATUS_NOT_DETECTED: dict(prob=50, result="No forms were detected to evaluate.", raw="No forms found", expected="Labeled, accessible forms",
                                        why="This isn't necessarily a problem — it simply means we couldn't evaluate a contact/lead form on the page reviewed.",
                                        rec_title=None),
         }),

    # ---------------- AI SEARCH & GEO READINESS ----------------
    dict(category="ai_geo", key="ai_crawler_access", name="AI Crawler Accessibility", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=60, result="Your robots.txt does not block major AI crawlers.", raw="GPTBot, ClaudeBot allowed", expected="AI crawlers not blocked",
                                why="If AI crawlers can't access your site, your business can't be referenced by AI-powered search and chat tools."),
             STATUS_WARNING: dict(prob=40, result="Some AI crawlers appear to be blocked in robots.txt.", raw="GPTBot disallowed", expected="AI crawlers not blocked",
                                   why="Blocking AI crawlers may prevent your business from appearing in AI-generated answers and recommendations.",
                                   rec_title="Allow AI Crawlers in Robots.txt", action="Review robots.txt and remove blanket disallows for major AI crawlers, if blocking wasn't intentional.",
                                   impact="AI search visibility", effort="Low", difficulty="Low"),
         }),
    dict(category="ai_geo", key="llms_txt", name="llms.txt Presence", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=20, result="An llms.txt file was found.", raw="/llms.txt found", expected="llms.txt present (optional signal)",
                                why="llms.txt is an emerging, optional convention for guiding AI tools to key content. It's one signal among many — not a ranking guarantee."),
             STATUS_NOT_DETECTED: dict(prob=80, result="No llms.txt file was found.", raw="Not found", expected="llms.txt present (optional signal)",
                                        why="llms.txt is an emerging, optional standard. Its absence is not a major issue today, but adding one is a low-effort way to help AI tools find your key pages.",
                                        rec_title="Consider Adding an llms.txt File", action="Add a simple llms.txt file pointing AI tools to your most important pages.",
                                        impact="Emerging AI-readiness signal", effort="Low", difficulty="Low"),
         }),
    dict(category="ai_geo", key="entity_clarity", name="Business Entity Clarity", weight=3,
         outcomes={
             STATUS_PASS: dict(prob=40, result="Your business name, services, and location are clearly stated in text and markup.", raw="Consistent entity signals", expected="Clear entity identification",
                                why="AI systems rely on clear, consistent facts to correctly identify and recommend your business."),
             STATUS_WARNING: dict(prob=45, result="Your business identity is only partially clear from the page content.", raw="Name found, service area unclear", expected="Clear entity identification",
                                   why="If AI tools can't clearly determine what you do and where you serve, they're less likely to recommend you for relevant queries.",
                                   rec_title="Clarify Business Identity & Services", action="Add a clear 'About' section stating your business name, services, and service area in plain language.",
                                   impact="AI & search entity recognition", effort="Medium", difficulty="Low"),
             STATUS_FAIL: dict(prob=15, result="Business identity signals are unclear or missing.", raw="Minimal identifying content", expected="Clear entity identification",
                                why="Without clear identity signals, both traditional search engines and AI tools struggle to understand and recommend your business.",
                                rec_title="Clarify Business Identity & Services", action="Add clear business name, service, and location information throughout the site and in structured data.",
                                impact="AI & search entity recognition", effort="Medium", difficulty="Medium"),
         }),
    dict(category="ai_geo", key="faq_content", name="FAQ / Q&A Content", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=35, result="Your site includes FAQ-style content.", raw="FAQ section detected", expected="FAQ / Q&A content present",
                                why="Question-and-answer content maps naturally to how people ask AI assistants questions, increasing the chance of being referenced."),
             STATUS_NOT_DETECTED: dict(prob=65, result="No FAQ or Q&A style content was detected.", raw="Not found", expected="FAQ / Q&A content present",
                                        why="AI tools frequently pull from question-and-answer formatted content. Without it, you may be missed for common customer questions.",
                                        rec_title="Add FAQ / Q&A Content", action="Add a FAQ section answering the most common questions prospects ask before hiring you.",
                                        impact="AI search visibility & user education", effort="Medium", difficulty="Low"),
         }),
    dict(category="ai_geo", key="trust_signals", name="Trust & Expertise Signals", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=40, result="Your site includes credibility signals (credentials, years in business, reviews, etc).", raw="Multiple trust signals found", expected="Visible trust/expertise signals",
                                why="Trust signals help both visitors and AI tools judge the credibility of your business."),
             STATUS_WARNING: dict(prob=60, result="Limited trust or expertise signals were found.", raw="Minimal trust content", expected="Visible trust/expertise signals",
                                   why="Without visible credibility markers, prospects and AI tools have less reason to trust and recommend your business over competitors.",
                                   rec_title="Add Trust & Expertise Signals", action="Highlight certifications, years in business, awards, and customer reviews prominently.",
                                   impact="Conversion & AI credibility signals", effort="Medium", difficulty="Low"),
         }),
    dict(category="ai_geo", key="content_freshness", name="Content Freshness", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=40, result="Content appears to be recently updated.", raw="Recent update signals found", expected="Regularly updated content",
                                why="Fresh content signals to search engines and AI tools that your business information is current and reliable."),
             STATUS_NOT_DETECTED: dict(prob=60, result="Unable to determine how recently content was updated.", raw="No date signals found", expected="Regularly updated content",
                                        why="This isn't necessarily a problem, but adding visible update dates (e.g. on blog posts) can help build freshness signals over time.",
                                        rec_title="Add Content Freshness Signals", action="Add publish/update dates to blog and service content, and refresh key pages periodically.",
                                        impact="Content freshness signal", effort="Low", difficulty="Low"),
         }),
    dict(category="ai_geo", key="service_definitions", name="Clear Service & Geographic Definitions", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=45, result="Services and service area are clearly and specifically described.", raw="Services + service area explicit", expected="Explicit service & area definitions",
                                why="Specific, explicit descriptions make it far easier for AI and search tools to match you to relevant local queries."),
             STATUS_WARNING: dict(prob=55, result="Services or service area are described vaguely.", raw="Generic descriptions", expected="Explicit service & area definitions",
                                   why="Vague descriptions make it harder for AI tools and search engines to confidently match you to specific customer needs.",
                                   rec_title="Clarify Services & Service Area", action="Explicitly list each service offered and every city/area served, rather than generic descriptions.",
                                   impact="Local & AI search matching", effort="Medium", difficulty="Low"),
         }),

    # ---------------- LINKS / AUTHORITY ----------------
    dict(category="authority", key="backlinks", name="Backlink Profile", weight=3,
         outcomes={
             STATUS_PASS: dict(prob=25, result="Your site has a healthy number of quality backlinks.", raw="142 backlinks", expected="Varies by competitive landscape",
                                why="Backlinks from other reputable sites remain one of the strongest ranking signals for competitive searches."),
             STATUS_WARNING: dict(prob=45, result="Your site has a modest backlink profile.", raw="23 backlinks", expected="Varies by competitive landscape",
                                   why="A limited number of backlinks can make it harder to outrank established competitors for competitive terms.",
                                   rec_title="Execute a Link Building Strategy", action="Pursue backlinks from local business directories, partners, industry associations, and press mentions.",
                                   impact="Domain authority & competitive rankings", effort="High", difficulty="Medium"),
             STATUS_FAIL: dict(prob=30, result="Very few or no backlinks were found.", raw="3 backlinks", expected="Varies by competitive landscape",
                                why="Minimal backlinks make it significantly harder to compete for search rankings against established competitors.",
                                rec_title="Execute a Link Building Strategy", action="Begin building citations and backlinks through directories, local partnerships, and content marketing.",
                                impact="Domain authority & competitive rankings", effort="High", difficulty="Medium"),
         }),
    dict(category="authority", key="referring_domains", name="Referring Domains", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=25, result="Links come from a healthy variety of unique domains.", raw="34 referring domains", expected="Diverse referring domains",
                                why="Links from many unique sites are generally more valuable than many links from the same site."),
             STATUS_WARNING: dict(prob=50, result="Links come from a limited number of unique domains.", raw="8 referring domains", expected="Diverse referring domains",
                                   why="A narrow set of referring domains provides a weaker authority signal than a more diverse link profile.",
                                   rec_title="Diversify Referring Domains", action="Seek links from a wider variety of relevant, reputable sources.",
                                   impact="Domain authority", effort="High", difficulty="Medium"),
             STATUS_FAIL: dict(prob=25, result="Very few unique referring domains were found.", raw="1 referring domain", expected="Diverse referring domains",
                                why="Almost no link diversity significantly limits your competitive authority.",
                                rec_title="Diversify Referring Domains", action="Begin outreach for links from local directories, partners, and industry sites.",
                                impact="Domain authority", effort="High", difficulty="Medium"),
         }),
    dict(category="authority", key="anchor_text", name="Anchor Text Diversity", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=50, result="Anchor text used in backlinks appears natural and varied.", raw="Varied anchor text", expected="Natural anchor text variety",
                                why="Natural anchor text variety looks organic to search engines, supporting a healthy link profile."),
             STATUS_NOT_DETECTED: dict(prob=50, result="Insufficient backlink data available to assess anchor text.", raw="Data unavailable", expected="Natural anchor text variety",
                                        why="This will be assessable once a backlink data source is connected.",
                                        rec_title=None),
         }),
    dict(category="authority", key="nofollow_ratio", name="Follow vs. Nofollow Links", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=45, result="A healthy mix of followed links point to your site.", raw="80% followed", expected="Majority followed links",
                                why="Followed links pass authority to your site, while nofollow links can still drive referral traffic and brand visibility."),
             STATUS_NOT_DETECTED: dict(prob=55, result="Insufficient backlink data available to assess follow/nofollow ratio.", raw="Data unavailable", expected="Majority followed links",
                                        why="This will be assessable once a backlink data source is connected.",
                                        rec_title=None),
         }),

    # ---------------- LOCAL SEO ----------------
    dict(category="local_seo", key="nap_consistency", name="NAP (Name, Address, Phone) Presence", weight=3,
         outcomes={
             STATUS_PASS: dict(prob=45, result="Business name, address, and phone number are clearly listed and consistent.", raw="NAP found in footer & contact page", expected="Consistent NAP across site",
                                why="Consistent NAP information helps both search engines and customers trust and find your business."),
             STATUS_WARNING: dict(prob=40, result="NAP information is present but incomplete or inconsistent.", raw="Phone missing on some pages", expected="Consistent NAP across site",
                                   why="Inconsistent contact information can confuse both customers and local search algorithms.",
                                   rec_title="Standardize NAP Information", action="Ensure your business name, address, and phone number are identical and visible on every page.",
                                   impact="Local search rankings & trust", effort="Low", difficulty="Low"),
             STATUS_FAIL: dict(prob=15, result="Business address or phone number could not be found on the site.", raw="Not found", expected="Consistent NAP across site",
                                why="Missing contact information hurts both local rankings and customer trust.",
                                rec_title="Add Complete NAP Information", action="Add your business name, address, and phone number prominently, ideally in the header/footer.",
                                impact="Local search rankings & trust", effort="Low", difficulty="Low"),
         }),
    dict(category="local_seo", key="localbusiness_schema", name="LocalBusiness Schema Markup", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=30, result="LocalBusiness structured data was found.", raw="Schema detected", expected="LocalBusiness schema present",
                                why="This structured data helps search engines display rich local business information directly in search results."),
             STATUS_NOT_DETECTED: dict(prob=70, result="No LocalBusiness structured data was found.", raw="Not found", expected="LocalBusiness schema present",
                                        why="Without this markup, search engines rely purely on unstructured page text to understand your business details.",
                                        rec_title="Add LocalBusiness Schema Markup", action="Implement LocalBusiness schema with your name, address, phone, hours, and service area.",
                                        impact="Local search visibility", effort="Medium", difficulty="Medium"),
         }),
    dict(category="local_seo", key="gbp_presence", name="Google Business Profile Signal", weight=2,
         outcomes={
             STATUS_WARNING: dict(prob=100, result="Unable to determine — Google Business Profile data is not yet connected.", raw="Data unavailable", expected="Connected GBP data source",
                                   why="A Google Business Profile is often the single biggest driver of local visibility. This will be assessed once the Local Visibility module is connected.",
                                   rec_title="Connect Google Business Profile Data", action="Once available, connect the GBP data source to evaluate profile completeness, reviews, and ranking signals.",
                                   impact="Local pack visibility", effort="Low", difficulty="Low"),
         }),
    dict(category="local_seo", key="service_area_pages", name="Service Area / Location Pages", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=30, result="Dedicated pages exist for key service areas.", raw="3 location pages found", expected="Location-specific content",
                                why="Location-specific pages help you rank for 'near me' and city-specific searches."),
             STATUS_WARNING: dict(prob=50, result="Service area is mentioned but lacks dedicated content.", raw="Mentioned in footer only", expected="Location-specific content",
                                   why="Without dedicated content per service area, you're less likely to rank for location-specific searches beyond your main city.",
                                   rec_title="Create Service Area Landing Pages", action="Build dedicated pages for each major city/area you serve, with locally relevant content.",
                                   impact="Local search rankings", effort="Medium", difficulty="Low"),
             STATUS_NOT_DETECTED: dict(prob=20, result="No clear service area information was found.", raw="Not found", expected="Location-specific content",
                                        why="Without a clearly defined service area, both customers and search engines may be uncertain where you operate.",
                                        rec_title="Define & Publish Your Service Area", action="Clearly state which cities/regions you serve, ideally with dedicated content per area.",
                                        impact="Local search rankings", effort="Medium", difficulty="Low"),
         }),

    # ---------------- SOCIAL, TRACKING & SECURITY ----------------
    dict(category="social_tracking_security", key="social_profiles", name="Linked Social Profiles", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=55, result="Multiple relevant social profiles are linked from the site.", raw="Facebook, Instagram linked", expected="Relevant active platforms linked",
                                why="Linked social profiles help build trust and give visitors another way to engage with your business."),
             STATUS_WARNING: dict(prob=45, result="Few or no social profiles are linked from the site.", raw="No social links found", expected="Relevant active platforms linked",
                                   why="This is a minor signal — not having every platform isn't a major issue, but linking active profiles builds trust.",
                                   rec_title="Link Active Social Profiles", action="Add links to your active, relevant social profiles (e.g. Facebook, Instagram) in the header or footer.",
                                   impact="Trust signals & engagement", effort="Low", difficulty="Low"),
         }),
    dict(category="social_tracking_security", key="open_graph", name="Open Graph / Social Sharing Tags", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=40, result="Open Graph tags are present for social sharing.", raw="og:title, og:image found", expected="Open Graph tags present",
                                why="Open Graph tags control how your page looks when shared on social media, improving click-through when people share your content."),
             STATUS_NOT_DETECTED: dict(prob=60, result="No Open Graph tags were found.", raw="Not found", expected="Open Graph tags present",
                                        why="Without these tags, shared links may show a blank or unattractive preview on social media.",
                                        rec_title="Add Open Graph Tags", action="Add Open Graph meta tags (title, description, image) to key pages.",
                                        impact="Social sharing appearance", effort="Low", difficulty="Low"),
         }),
    dict(category="social_tracking_security", key="analytics", name="Analytics / Tracking Installed", weight=2,
         outcomes={
             STATUS_PASS: dict(prob=55, result="An analytics platform was detected.", raw="Google Analytics detected", expected="Analytics installed",
                                why="Analytics data is essential for understanding visitor behavior and measuring marketing ROI."),
             STATUS_FAIL: dict(prob=45, result="No analytics or tracking platform was detected.", raw="Not detected", expected="Analytics installed",
                                why="Without analytics, you have no visibility into how visitors find and use your site, making it hard to measure marketing performance.",
                                rec_title="Install Website Analytics", action="Install Google Analytics (or similar) and Google Tag Manager to track visitor behavior and conversions.",
                                impact="Marketing measurement", effort="Low", difficulty="Low"),
         }),
    dict(category="social_tracking_security", key="email_security", name="Email/Domain Security (SPF & DMARC)", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=35, result="SPF and DMARC records are configured.", raw="SPF + DMARC found", expected="SPF & DMARC present",
                                why="These records help prevent your domain from being spoofed in phishing emails, protecting your brand reputation."),
             STATUS_WARNING: dict(prob=45, result="SPF is configured, but DMARC is missing.", raw="SPF found, DMARC missing", expected="SPF & DMARC present",
                                   why="Without DMARC, your domain is more vulnerable to email spoofing, which can damage customer trust.",
                                   rec_title="Add a DMARC Record", action="Publish a DMARC DNS record to strengthen email security and brand protection.",
                                   impact="Email deliverability & brand protection", effort="Low", difficulty="Medium"),
             STATUS_FAIL: dict(prob=20, result="No SPF or DMARC records were found.", raw="Not found", expected="SPF & DMARC present",
                                why="Without SPF/DMARC, it's easier for bad actors to send spoofed emails that appear to come from your domain.",
                                rec_title="Configure SPF & DMARC Records", action="Add SPF and DMARC DNS records to protect your domain from email spoofing.",
                                impact="Email deliverability & brand protection", effort="Low", difficulty="Medium"),
         }),
    dict(category="social_tracking_security", key="hsts", name="HSTS Header", weight=1,
         outcomes={
             STATUS_PASS: dict(prob=30, result="HSTS is enabled, enforcing secure connections.", raw="Strict-Transport-Security header found", expected="HSTS enabled",
                                why="HSTS tells browsers to always use HTTPS for your domain, protecting visitors from downgrade attacks."),
             STATUS_NOT_DETECTED: dict(prob=70, result="HSTS header was not detected.", raw="Not found", expected="HSTS enabled",
                                        why="Without HSTS, there's a small window where a visitor's first connection could be intercepted before redirecting to HTTPS.",
                                        rec_title="Enable HSTS", action="Add the Strict-Transport-Security header via your server or CDN configuration.",
                                        impact="Security hardening", effort="Low", difficulty="Medium"),
         }),
]


def run_checks(site_profile: dict) -> list[dict]:
    """Roll deterministic outcomes for every check in the catalog.

    Returns a list of dicts shaped for direct persistence as AuditCheck rows
    (see models.AuditCheck), plus recommendation fields when the outcome
    signals a fix is available.
    """
    rng = random.Random(site_profile["seed"])
    results = []
    for check_def in CHECK_CATALOG:
        status = _pick(rng, check_def["outcomes"])
        outcome = check_def["outcomes"][status]
        results.append({
            "category": check_def["category"],
            "key": check_def["key"],
            "name": check_def["name"],
            "weight": check_def["weight"],
            "status": status,
            "result": outcome["result"],
            "raw_value": outcome.get("raw"),
            "expected_value": outcome.get("expected"),
            "business_explanation": outcome.get("why"),
            "data_source": site_profile.get("data_source", "sample_data"),
            # Recommendation fields (present only for actionable non-pass outcomes)
            "rec_title": outcome.get("rec_title"),
            "rec_action": outcome.get("action"),
            "rec_impact": outcome.get("impact"),
            "rec_effort": outcome.get("effort"),
            "rec_difficulty": outcome.get("difficulty"),
        })
    return results
